# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameasure',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
