# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-16 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartApp', '0003_auto_20180716_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationuser',
            name='station_name',
            field=models.CharField(max_length=255),
        ),
    ]
